version: '3.2'
services:
  api:
    init: true
    network_mode: host
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./docker_volume:/app/docker_volume
    depends_on:
      - mongo_information_extraction
  queue_processor_information_extraction:
    init: true
    network_mode: host
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: Dockerfile
      target: queue_processor_information_extraction
    shm_size: '11gb'
    volumes:
      - ./docker_volume:/app/docker_volume
    depends_on:
      - mongo_information_extraction
  mongo_information_extraction:
    network_mode: host
    restart: unless-stopped
    command: mongod --port 29017
    image: "mongo:4.0.1"
  redis_information_extraction:
    network_mode: host
    restart: unless-stopped
    image: "redis:5.0.14"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - testing