version: "3.8"
services:
  pdf_metadata_extraction_api:
    container_name: pdf_metadata_extraction_api
    entrypoint: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--chdir", "./src", "app:app", "--bind", "0.0.0.0:5056", "--timeout", "300"  ]
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/docker_volume
    depends_on:
      - pdf_metadata_extraction_worker
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SENTRY_DSN=${SENTRY_DSN:-}
    ports:
      - "5056:5056"
    env_file: .env
    networks:
      - pdf_metadata_extraction_network
  pdf_metadata_extraction_worker:
    container_name: pdf_metadata_extraction_worker
    init: true
    entrypoint: [ "python3", "-m", "src.QueueProcessor" ]
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/docker_volume
    shm_size: '11gb'
    depends_on:
      - mongo_metadata_extraction
      - redis_metadata_extraction
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SENTRY_DSN=${SENTRY_DSN:-}
    networks:
      - pdf_metadata_extraction_network
    env_file: .env
  mongo_metadata_extraction:
    restart: unless-stopped
    command: mongod --port 29017
    image: "mongo:7.0.12"
    networks:
      - pdf_metadata_extraction_network
    ports:
      - "29017:29017"
  redis_metadata_extraction:
    restart: unless-stopped
    image: "redis:7.2.5"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - pdf_metadata_extraction_network
    ports:
      - "6379:6379"
networks:
  pdf_metadata_extraction_network:

volumes:
  data: